name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - folium
  - wordcloud
  - matplotlib
  - pandas
  - scipy  
  - gensim
  - nltk
  - pip
  - pip:
    - jupyter
