name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - folium
  - wordcloud
  - matplotlib
  - pandas
  - gensim
  - nltk
  - cython
  - gcc
  - make
  - pip:
    - jupyter
