name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy=1.22.4
  - folium
  - wordcloud
  - matplotlib
  - scipy=1.8.1
  - gensim=4.1.2
  - nltk
  - pip
  - pip:
    - jupyter
