name: environment
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - numpy
    - wordcloud
    - matplotlib
    - pandas
    - gensim
    - nltk
    - json
    - ast
    - os
  - python
  - numpy
  - wordcloud
  - matplotlib
  - pandas
  - gensim
  - nltk
  - json
  - ast
  - os
  

