name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy==1.10.1
  - numpy
  - folium
  - wordcloud
  - matplotlib
  - pandas
  - gensim==4.3.1
  - nltk==3.8.1
  - cython
  - pip
  - pip:
    - jupyter
