name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - numpy
  - folium
  - wordcloud
  - matplotlib
  - pandas
  - pip
  - pip:
    - gensim==4.1.2
    - nltk
    - jupyter
